name: taxi.fail.chk
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: '%Y%m%d-%H%M%S-my-run-name-template'
expectation_suite_name: 'demo_taxi_fail'
batch_request:
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: bigquery_datasource
      data_connector_name: default_inferred_data_connector_name
      data_asset_name: great_expectations_bigquery_example.taxi
      batch_spec_passthrough:
        bigquery_temp_table: great_expectations_bigquery_example.taxi_temp

profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id: